# Importando as Bibliotecas

In [1]:
import pandas as pd
import re

print("Bibliotecas Salvas com Sucesso!!")

Bibliotecas Salvas com Sucesso!!

# Leitura da Base de Dados

In [3]:
dados = pd.read_csv("../data/dataset_tratado.csv", index_col=0)
dados.head()

                               review_comment_message  review_score sentimento
3               Recebi bem antes do prazo estipulado.             5   positivo
4   Parabéns lojas lannister adorei comprar pela I...             5   positivo
9   aparelho eficiente. no site a marca do aparelh...             4   positivo
12    Mas um pouco ,travando...pelo valor ta Boa.\r\n             4   positivo
15  Vendedor confiável, produto ok e entrega antes...             5   positivo

# 1. Pré-Processamento

## Limpando o Texto

In [6]:
CONTRACTIONS = {
    'vc': 'você', 'tb': 'também', 'tbm': 'também', 'pq': 'por que', 'obg': 'obrigado', 'blz': 'beleza',
    'td': 'tudo', 'msm': 'mesmo', 'vlw': 'valeu', 'n': 'não', 'naum': 'não', 'cmprar': 'comprar',
    'mt': 'muito', 'pra': 'para'
}

In [7]:
def limpar_texto(texto):

    # 1. Lowercase
    texto = texto.lower()
    # 2. Remove HTML
    texto = re.sub(r'<[^>]+>', ' ', texto)
    # 3. Remove URLs
    texto = re.sub(r'http\S+|www\.\S+', ' ', texto)
    # 4. Remove e-mails
    texto = re.sub(r'\S+@\S+', ' ', texto)
    # 5. Expande contrações
    palavras = [CONTRACTIONS.get(p,p) for p in texto.split()]
    texto = ' '.join(palavras)

    # 6. Remove caracteres indesejados
    texto = re.sub(r'[^a-záàâãéêèíìîóôõöúùûüç\s.,!?]', ' ', texto)

    # 7. Normaliza espaços
    texto = re.sub(r'\s+', ' ', texto).strip()

    return texto

In [8]:
# Fazendo um teste da função
teste = "<p>ADOREI o produto!!! vc precisa comprar tbm https://loja.com</p>"
resultado = limpar_texto(teste)
print(resultado)

adorei o produto!!! você precisa comprar também

In [9]:
dados['texto_limpo'] = dados['review_comment_message'].apply(limpar_texto)
dados.head()

,review_comment_message,review_score,sentimento,texto_limpo
3,Recebi bem antes do prazo estipulado.,5,positivo,recebi bem antes do prazo estipulado.
4,Parabéns lojas lannister adorei comprar pela I...,5,positivo,parabéns lojas lannister adorei comprar pela i...
9,aparelho eficiente. no site a marca do aparelh...,4,positivo,aparelho eficiente. no site a marca do aparelh...
12,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",4,positivo,"mas um pouco ,travando...pelo valor ta boa."
15,"Vendedor confiável, produto ok e entrega antes...",5,positivo,"vendedor confiável, produto ok e entrega antes..."

## Tokenização - Quebrando texto em unidades

In [16]:
import nltk

nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

from nltk.tokenize import word_tokenize

In [17]:
modelo = "Eu sou cientista de dados"

tokens = word_tokenize(modelo, language="portuguese")
print(tokens)

['Eu', 'sou', 'cientista', 'de', 'dados']

In [20]:
def tokenizacao(texto):

    return word_tokenize(texto, language="portuguese")

In [21]:
dados["tokens"] = dados["texto_limpo"].apply(tokenizacao)

dados[["texto_limpo", "tokens"]].head()

,texto_limpo,tokens
3,recebi bem antes do prazo estipulado.,"[recebi, bem, antes, do, prazo, estipulado, .]"
4,parabéns lojas lannister adorei comprar pela i...,"[parabéns, lojas, lannister, adorei, comprar, ..."
9,aparelho eficiente. no site a marca do aparelh...,"[aparelho, eficiente, ., no, site, a, marca, d..."
12,"mas um pouco ,travando...pelo valor ta boa.","[mas, um, pouco, ,, travando, ..., pelo, valor..."
15,"vendedor confiável, produto ok e entrega antes...","[vendedor, confiável, ,, produto, ok, e, entre..."